### ISSUE TITLE
Support python 3.6, or perhaps arbitrary versions of python

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs-docker-images#16]
Now that 3.6 is released, it would be a good idea to add this to at least the 16.04 image, assuming this can be done easily without removing the 3.5 version.

One approach could be to use pyenv to build arbitrary versions, allowing for support of arbitrary versions of pypy as well.

The `docs` user on the docker image should be able to call the python binaries by the short binary names: `python2.7`, `python3.5`, `python3.6`, etc. These will need to be on the user's `PATH` in some fashion. It isn't necessary to have system level binaries for all versions, however they are preferred due to security concerns. A PPA could be used, as long as it is vetted a bit -- compiled binaries might be more trusted here because of this.

## Testing

These images should be able to be spun up and the binaries should be able to be called by the `docs` user. `pip` and `virtualenv` should be installed for each version separately.

**Comment by Zopieux** [comment]
Yes please! 3.6 introduces so many great changes it would be a shame to lag behind.

Python 3.6 [seems](http://packages.ubuntu.com/search?arch=amd64&keywords=python3.6) to be included in ubuntu 16.10.

**Comment by agjohnson** [comment]
We only use LTS images for Ubuntu to reduce maintenance there, but @agronholm has put together a container image that uses pyenv that should give access to python(2.7,3.4,3.5,3.6). I'm testing some changes to it now, but the image will likely be our next development image that folks can self select into, with our Ubunutu 16.04 build image becoming the default builder very shortly.

**Comment by Zopieux** [comment]
Seems fine too.

**Comment by agjohnson** [comment]
Closing this with #18, but it will be a short while to get all the other pieces together and get a release out to support this.

**Comment by Zopieux** [comment]
@agjohnson is there a way to get notified when 3.6 becomes available in rtd.org? A follow-up on this issue would be perfect.
