### ISSUE TITLE
Is it possible to use this docker image to build my docs locally?

### ISSUE THREAD

**Issue by qiuwch** [rtfd/readthedocs-docker-images#38]
I read this page http://docs.readthedocs.io/en/latest/builds.html and found this repository.

I am having some issues with building my docs in the readthedocs service, while my local sphinx-build works perfectly. I want to know whether I can use this docker image to reproduce the building procedure in my dev box. This will greatly simplify my development.

I also read this https://github.com/rtfd/readthedocs-docker-images/blob/master/CONTRIBUTING.rst and found the template project can not be built, because it reports sphinx-build not found.

Thanks.

**Comment by agjohnson** [comment]
@qiuwch You can use these images for that, though you will need to replicate the build steps manually. This will involve all of the normal steps you might see on a build output page for your project on Read the Docs. It involves setting up a virtualenv, installing the base dependencies, your dependencies, then attempting the build. We still trying to make the local builds as reproducible as possible, https://github.com/rtfd/readthedocs-build was our initial attempt at this.
