### ISSUE TITLE
Documentation on image usage

### ISSUE THREAD

**Issue by niekbosch** [rtfd/readthedocs-docker-images#5]
Is there any documentation on how this image is used by the build system? It apparently does not contain a complete build environment. For example, it misses Sphinx. What more tools should be installed in the container, or do I need tools outside the container to build my documentation?

My goal is to have a Docker image, which I can use to build the documentation locally for test purposes.

Thanks in advance for any help.

**Comment by agjohnson** [comment]
These images are strictly for our internal build system, they don't have much use outside that. The RTD build system creates a container from these images, mounts internal build paths, and then performs the rest of the setup, including virtualenv set up (installing Sphinx) and performing the Sphinx build. You need a full RTD instance for these images to be of much use.

You'll need to simulate mounting the project path and calling sphinx manually, if you wish to test this locally, without RTD.

**Comment by niekbosch** [comment]
Thank you for your reply. I think I managed quit well: https://github.com/sara-nl/griddocs

I still used your images and for now did not find any differences in the way the documentation is parsed.
