### ISSUE TITLE
Auto conda version test

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs-docker-images#50]
The auto test that checks the conda version is something good to have, but it's only ran on new PRs, so if nobody touches the repository we will end up with an outdated conda version anyway.

In fact, at this moment we have `4.3.30` and the latest is `4.4.3`.

https://github.com/conda/conda/blob/master/CHANGELOG.md

See #49

**Comment by humitos** [comment]
I just realized that I got confused with the versions, since `miniconda` and `conda` are not the same thing and I was looking at `conda` but we are using `miniconda`.

Anyway, the problem that this is running only on new PRs is still present.

**Comment by agjohnson** [comment]
It runs against master via a cron, not using a PR. So as soon as the linux miniconda version changes, we start getting daily alerts. I've been getting these for a few days from Travis

**Comment by humitos** [comment]
OK, thanks for the explanation. I'm closing this issue since there is nothing wrong or to do.
