### ISSUE TITLE
Make imagemagick available at docker images

### ISSUE THREAD

**Issue by caduvieira** [rtfd/readthedocs-docker-images#70]
To be able to use sphinx plugin sphinx.ext.imgconverter to convert svg to png we need imagemagick available.

Refers: https://github.com/rtfd/readthedocs.org/issues/3979

**Comment by mgeier** [comment]
@caduvieira IMHO it looks better most of the time if SVG images are converted to PDF images (instead of PNG) by using the `sphinxcontrib-svg2pdfconverter` module, which does the conversion without rasterizing the image.

See #78 and #79.

**Comment by humitos** [comment]
Hi all! `imagemagick` was installed in our latest testing image `5.0rc1` (not released yet). I'd like to know if you want to help us testing it. In that case, please let me know what are the projects you are interested on testing it and I will apply this Docker image for its building process.

**Comment by caduvieira** [comment]
The project is:
servicosgovbr/manual-avaliacao
https://readthedocs.org/projects/manual-avaliacao/

The SVG image is in this anchor:
https://manual-avaliacao.readthedocs.io/pt_BR/latest/apresentacao.html#fluxo-simplificado-das-apis

Could you please test it? Thanks!

**Comment by humitos** [comment]
Hi @caduvieira! I enabled the new Docker image to your project and I triggered a new build of `latest` version. Please, let me know if it did work as you expected. Thanks!

**Comment by humitos** [comment]
@caduvieira it seems that you don't have the extension enabled/installed in your `conf.py`; https://github.com/rtfd/readthedocs.org/issues/3979#issuecomment-438817577
