### ISSUE TITLE
Add Python 3.7

### ISSUE THREAD

**Issue by scolby33** [rtfd/readthedocs-docker-images#72]
I'd love to be able to build my docs for a Python 3.7-only project on RTD.

Since you're using `pyenv` from git, is it possible to add Python 3.7 to the rtd/build 3.x line of images, or will we have to wait until you switch to the 18.04-based image?

**Comment by agjohnson** [comment]
Yup! This would be a great addition. We were waiting for an actual release of 3.7 before adding to the image here. It's been out for a bit, but we've had very little bandwidth for this.

Targeting 4.1 image for this.

**Comment by webknjaz** [comment]
The related PR #73 is ready to be merged ;)

**Comment by vEpiphyte** [comment]
I added notes to rtfd/readthedocs-docker-images#73 if there is a urgent need for 3.7 support for doc building using `conda` as a workaround for now.
