### ISSUE TITLE
Include part of README into docs

### ISSUE THREAD

**Issue by webknjaz** [rtfd/readthedocs-docker-images#77]
Docs https://docs.readthedocs.io/en/latest/yaml-config.html#build-image don't list everything present in the README of this repo.

I suggest using partial inclusion to synchronize them: https://muffinresearch.co.uk/selectively-including-parts-readme-rst-in-your-docs/.

**Comment by stsewd** [comment]
Do you mean 1.0 and 4.0rc images? We don't support those yet on rtd

**Comment by stsewd** [comment]
Also, the yaml config docs are located in another repo https://github.com/rtfd/readthedocs.org/tree/master/docs

**Comment by webknjaz** [comment]
Probably 3.0 as well (not stated that it's latest)...

**Comment by stsewd** [comment]
Yeah, we are planning to change numbered versions to just `stable` and `latest` https://github.com/rtfd/readthedocs-docker-images/issues/62
